apiVersion: v1
kind: Service
metadata:
  name: spring-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32324
    protocol: TCP
  selector:
    app: ToyStore-secrets 
  type: NodePort
