apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: default
data:
spring.datasource.url:jdbc:mysql://35.188.180.98:32324/toystore
spring.datasource.username:root
spring.datasource.password:ahmed


